.TL 
My First Groff Document
.AU 
Chris 
.AI
Zhengzhou University
.NH
Introduction
.PP
This is a paragraph.
.NH
Second section
.NH 2
Subsection title
.PP
subsection text
.NH 3
subsubsection title
.PP
Subsubsection text

.PP
.sp 4
My thoughts on the subject
.sp

.PP
.ce 1000
lines to center 
.ce 0

lines to head
.PP
Here is more text here, I'm trying use groff.
I want the word
.B "bold"
to be bold. 

We can have
.I "italic text"
with .I.
.BI "This is the bold italic text"
